# fly.toml app configuration file generated for currency-alarm on 2025-10-05T20:12:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "currency-alarm"
primary_region = "gru"

[build]

[env]

[processes]
  worker = "/usr/local/bin/run-app"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1