# fly.toml app configuration file generated for currency-alarm on 2025-10-05T20:12:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "currency-alarm"
primary_region = "gru"

[build]

[env]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1